CREATE TABLE TBL_MEMBER (
	USERID VARCHAR(50) NOT NULL,
    USERPW VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    REGDATE TIMESTAMP DEFAULT NOW(),
    UPDATEDATE TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(USERID)
    );